---
abstract: Test library that can be run in two modes; one to generate outputs and a
  second to compare against them
author:
- Nicholas Bamber <nicholas@periapt.co.uk>
build_requires:
  DirHandle: '0'
  File::Spec: '0'
  Test::MockObject: '0'
configure_requires:
  Module::Build: '0.40'
dynamic_config: 1
generated_by: Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921
keywords:
- Test
- Regression
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Regression
provides:
  Test::Regression:
    file: lib/Test/Regression.pm
    version: '0.07'
requires:
  Algorithm::Diff: '0'
  FileHandle: '0'
  Test::Differences: '0'
  Test::More: '0'
  Text::Diff: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/periapt/test-regression/tree
version: '0.07'
